# Database
db.url=jdbc:postgresql://localhost:5432/db_gateway
db.user=kernel
db.password=1234

# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.group.id=wsprovider
kafka.topic=sislem-topic

# File
catalog.file=Embarcaciones.txt